thebrowsercompany/swift-winrt

.github/actions/windows-build/action.yml
swiftwinrt/Resources/CWinRT/CppInteropWorkaround.h
swiftwinrt/Resources/Support/CppInteropWorkaround.swift

A new version of the Swift toolchain includes the fix for `wchar_t` in C++ interop, so we can remove the workaround.

Remove the C++ interop workaround for wchar_t

---

swiftwinrt/Resources/Support/Events/EventSource.swift
swiftwinrt/Resources/Support/GUID.swift
swiftwinrt/code_writers.h
tests/test_component/Sources/test_component/Windows.Foundation.Collections.swift
tests/test_component/Sources/test_component/Windows.Foundation.swift
tests/test_component/Sources/test_component/test_component.swift

with the latest swift toolchain, there are a bunch of warnings for retroactive protocol conformance. while there are valid concerns with this usage, for the bindings it isn't a problem because we own the whole type system.

add retroactive to suppress warnings

---

.github/workflows/nuget-public.yml
.github/workflows/publish.yml
CMakeLists.txt

This is useful for one-off builds, so I can have `0.0.42-tryingthingsout`.
Also renamed `NUGET_VERSION[_*]` variables to `NUGET_PACKAGE_VERSION[_*]`, since in one file it's used to refer to the version of `nuget.exe` and in another to the version of the published package, leading to confusion.

Support a prerelease identifier when manually publishing to nuget

---

swiftwinrt/code_writers.h
tests/test_app/AsyncTests.swift
tests/test_app/main.swift
tests/test_app/test_app.exe.manifest
tests/test_component/Sources/CWinRT/include/test_component.h
tests/test_component/Sources/test_component/Windows.Foundation.swift
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component+MakeFromAbi.swift
tests/test_component/Sources/test_component/test_component.swift
tests/test_component/cpp/AsyncMethods.cpp
tests/test_component/cpp/AsyncMethods.h
tests/test_component/cpp/AsyncMethods.idl
tests/test_component/cpp/AsyncOperationInt.cpp
tests/test_component/cpp/AsyncOperationInt.h
tests/test_component/cpp/CMakeLists.txt
tests/test_component/cpp/test_component.idl

`IAsync***.get()` enforced execution on the `MainActor`, but this breaks unit tests where there might not be a `MainActor` running a message loop. WinRT `IAsync***` don't have a built-in requirement that they need to be invoked on the main thread, so we shouldn't implicitly do that. If we find an async API returning a ui-thread bound object which misbehaves with the completion handler and `getResults()` call happening on a background thread, we can add an additional method that enforces that these happen on the MainActor.
Also fixes errors/cancelations not being surfaced on `IAsyncAction`s after awaiting
Adds tests for awaiting `IAsyncOperation`s: success vs failure cases, and "already completed" vs suspension cases.
Fixes WIN-842

Don't require the MainActor for awaiting IAsync[Action/Operation]'s

---

.github/workflows/publish.yml

Fix tested here:
With suffix: https://github.com/thebrowsercompany/swift-winrt/actions/runs/6723802926/job/18275145871#step:5:229
Without suffir: https://github.com/thebrowsercompany/swift-winrt/actions/runs/6723802926/job/18275145871#step:5:229

Fix syntax for release workflow

---

tests/test_app/AsyncTests.swift

I had one case of the release workflow failing due to a timeout. 100ms may have been aggressively short, so bump it to 1s.

Extend async test timeouts to prevent flakiness

---

swiftwinrt/Resources/Support/Aggregation.swift
swiftwinrt/Resources/Support/Marshaler.swift
swiftwinrt/Resources/Support/WinRTWrapperBase.swift
swiftwinrt/code_writers.h
swiftwinrt/code_writers/common_writers.h
swiftwinrt/helpers.h
swiftwinrt/types.cpp
tests/test_component/Sources/test_component/Windows.Foundation+ABI.swift
tests/test_component/Sources/test_component/Windows.Foundation+Impl.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections+ABI.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections+Impl.swift
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Generics.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component.Delegates+ABI.swift
tests/test_component/Sources/test_component/test_component.Delegates+Impl.swift
tests/test_component/Sources/test_component/test_component.swift

we have different wrappers/bridge types which are used for wrapping/unwrapping pointers from the ABI. These are more "complex" scenarios, like:
1. projecting `IReference<T>` as `T?` in Swift
2. projecting/unwrapping composable classes
3. unwrapping interfaces
4. projecting `delegate` as function in Swift
Simple value type or non-composable classes are straightforward to return from the ABI.
Prior to this change, scenarios 1 and 2 used the same base `WinRTWrapperBase` but did other things slightly differently. The purpose of this change was two fold:
1. make all the wrappers derive from the same base wrapper class which uses the `AbiBridge` protocol for defining how the types are bridged. The main reason here is for follow up changes to fix ref count issues. this will let those changes be …

consolidate bridge and wrapper implementations

---

swiftwinrt/Resources/Support/Aggregation.swift
swiftwinrt/Resources/Support/IInspectable.swift
tests/test_app/AggregationTests.swift
tests/test_component/Sources/CWinRT/include/test_component.Delegates.h
tests/test_component/Sources/CWinRT/include/test_component.h
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component.Delegates+ABI.swift
tests/test_component/Sources/test_component/test_component.Delegates+Impl.swift
tests/test_component/Sources/test_component/test_component.Delegates.swift
tests/test_component/Sources/test_component/test_component.swift
tests/test_component/cpp/Class.h
tests/test_component/cpp/test_component.idl

with fixing memory leaks and adding the `WinRTClassWeakReference` class, this caused a regression in unwrapping them as `Any` where we'd simply return the `WinRTClassWeakReference` type. This manifested in Arc for event handlers, where the sender parameter is `Any`. When unwrapping `Any` objects, we should check for the type being one of these and return the object its holding instead
1. Add `AnyObjectWrapper` protocol and check for this in the `__ABI.AnyWrapper` when unwrapping objects
2. Add conformance of `AnyObjectWrapper` to `WinRTClassWeakReference`. 
3. Added tests case
Fixes WPP-795

fix unwrapping winrtweakreference

---

swiftwinrt/Resources/Support/Array+toVector.swift

Ran into a crash when using `toVector` due to a missing iterator - wondering if this will help!
Tested with this feature: https://github.com/thebrowsercompany/arc/pull/19433 and was able to verify that this mitigated the crash!

Add iterator implementation for array-to-vector support

---

swiftwinrt/code_writers.h
swiftwinrt/type_writers.h
tests/test_component/Sources/CWinRT/include/test_component.h
tests/test_component/Sources/test_component/Windows.Foundation.Collections.swift
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component.swift
tests/test_component/cpp/BaseCollection.h
tests/test_component/cpp/test_component.idl

for composable classes with generic default interfaces, we were incorrectly writing type names like `IVector<Foo>`, which aren't valid swift type names. This uses the same `bind_type_abi` method we use for removing the brackets and writing a name like `IVectorFoo` instead.
This error didn't manifest itself until trying to use the `ThemeShadow` class which resulted in `UIWeakElementCollection` being generated, which is unsealed.
1. description above
2. Had to change `typealias SwiftABI = IVectorFoo` to the full name since there is a naming collision now
3. updated one of the class definitions to be unsealed to verify the fix works
Fixes WIN-1015

fix writing composable impl for generic default interfaces

---

swiftwinrt/code_writers.h
swiftwinrt/code_writers/struct_writers.cpp
tests/test_app/main.swift
tests/test_component/Sources/CWinRT/include/test_component.h
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Generics.swift
tests/test_component/Sources/test_component/test_component.swift
tests/test_component/cpp/Simple.h
tests/test_component/cpp/test_component.idl

when someone tries to include a struct with reference types, the code gen breaks for a few reasons:
1. in the constructor of the projected struct, we were using `IReference<T>` instead of `T?`
2. in the abi conversion code, we weren't converting between the ABI and swift types appropriately
- for (1) above, use the `write_type` api
- for (2) above, check if the member type is an ireference and appropriately set the value
added test cases
Fixes WIN-450

fix ireference usage in structs

---

swiftwinrt/code_writers/type_writers.cpp
swiftwinrt/helpers.h
swiftwinrt/types.cpp
swiftwinrt/types.h
tests/test_component/Sources/CWinRT/include/test_component.h
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Generics.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component+MakeFromAbi.swift
tests/test_component/Sources/test_component/test_component.swift
tests/test_component/cpp/CollectionTester.idl

in #134 I missed a case in `type_writers.cpp` where we were no longer writing the full GUID name.
also added some cleaning up around checking for the GUID type so things aren't done by string checking which was broken inadvertently

fix uuid name

---

nuget/swiftwinrt.nuspec

nuget upload is failing with the following error:
`Response status code does not indicate success: 400 (The readme file 'readme.md' does not exist in the package.).`
this must be due to the casing of the README.md file...very odd
also fixed up the project url while here

fix nuget upload to nuget.org

---

swiftwinrt/code_writers.h
swiftwinrt/code_writers/type_writers.cpp
tests/test_component/Sources/test_component/test_component+Generics.swift

this fully qualifies the C++ type name by using the new `write_type` api

hopefully the last one

---

swiftwinrt/code_writers.h
swiftwinrt/code_writers/common_writers.h
swiftwinrt/helpers.h
tests/test_component/Sources/CWinRT/include/test_component.h
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component.swift
tests/test_component/cpp/Base.h
tests/test_component/cpp/BaseNoOverrides.h
tests/test_component/cpp/Derived.h
tests/test_component/cpp/Keywords.idl
tests/test_component/cpp/test_component.idl

These fixes were required to get the `Microsoft.Graphics.Canvas` WinMD to build, the few things that this winmd uncovered:
1. Simply deriving from an interface resulted in not properly tracking dependencies. 
2. `subscript` is a method and needs to be escaped with backticks
3. There are static methods which technically "override" others (they have the same name, num of params and return types are related). These need to be marked as `class` methods and the derived types have to say `override`  
1. add `w.add_depends` in some places where we don't use any of the `write(type)` methods. We don't use those methods because swift name requirements for deriving from a generic interface don't follow "normal" (as in what most other languages do - where you need `IFoo` instead of `IFoo<Bar>`) …

fixes for Win2D to build

---

swiftwinrt/code_writers.h
tests/test_app/WinRTInterfaceImplementations.swift
tests/test_component/Sources/test_component/Windows.Foundation+ABI.swift
tests/test_component/Sources/test_component/Windows.Foundation+Impl.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections.swift
tests/test_component/Sources/test_component/Windows.Foundation.swift
tests/test_component/Sources/test_component/Windows.Storage+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.swift
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Generics.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component.Delegates+ABI.swift
tests/test_component/Sources/test_component/test_component.Delegates+Impl.swift
tests/test_component/Sources/test_component/test_component.Delegates.swift
tests/test_component/Sources/test_component/test_component.swift

delegates need to be marked throwing so app code can handle errors from winrt listeners which fail
i'm sure this will make @tristanlabelle happy :D

make delegates throwing

---

swiftwinrt/code_writers.h
tests/test_app/AggregationTests.swift
tests/test_app/AsyncTests.swift
tests/test_app/BufferTests.swift
tests/test_app/CollectionTests.swift
tests/test_app/EventTests.swift
tests/test_app/main.swift
tests/test_component/Sources/test_component/Windows.Foundation.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams.swift
tests/test_component/Sources/test_component/Windows.Storage.swift
tests/test_component/Sources/test_component/test_component.swift

Currently instance functions throw but static functions do not. There is no reason for this difference, so align on making all functions throw to make their errors possible to handle.
Fixes #145

Make static functions throw just like instance functions

---

.github/workflows/pull-request.yml
CMakePresets.json

swift-winrt cant build using clang and #151 also breaks building it in Visual Studio as well as inner-loop for folks trying to debug in VSCode. since the test app is built using SPM, specifying clang doesn't do anything so we should be able to remove it entirely

fix inner loop by removing clang

---

.vscode/launch.json
CMakePresets.json
swiftwinrt/Resources/Support/HString.swift

When an `HString `is currently constructed, the `withCString` method makes a copy of the source string for null termination. Then `WindowsCreateString` created a second copy.  An `HSTRING` doesn't need a null terminated string for construction, so remove `withCString ` and use a single allocation by `WindowsPreallocateStringBuffer`. 
The contents of the source string are copied into the `HSTRING_BUFFER` created by `WindowsPreallocateStringBuffer`, and an `HSTRING` is created from that buffer using `WindowsPromoteStringBuffer`.
Fixes DEVIN-1237

Remove an extra string copy while constructing HString

---

tests/test_app/CollectionTests.swift
tests/test_component/cpp/CollectionTester.cpp
tests/test_component/cpp/CollectionTester.h
tests/test_component/cpp/CollectionTester.idl

Adds a skipped test that would pass if #159 were implemented.
I believe this doesn't work and would be nontrivial to implement. When a Swift-implemented `IVector<T>` is passed to WinRT, we create a COM-exposable wrapper specific to top-level interface, `IVector<T>`, but that wrapper does not know how to provide additional required interfaces, `IIterable<T>` in this case. More generally, the wrapper would have no way to know that the Swift object implements other interfaces (for example `IClosable`). `IVector<T>`'s queryInterface cannot respond to `IIterable<T>` because the GUID and wrapper types are different for each `T`.

Add test for IVector being IIterable

---

swiftwinrt/code_writers/struct_writers.cpp
tests/test_component/Sources/test_component/Windows.Data.Text.swift
tests/test_component/Sources/test_component/Windows.Foundation.swift
tests/test_component/Sources/test_component/Windows.Storage.Search.swift
tests/test_component/Sources/test_component/test_component.swift

Structs are `Sendable` by definition:
> Structs are always passed and returned by value. Struct fields may only be primitives, enums, structs, strings, and [IReference<T>](https://learn.microsoft.com/en-us/uwp/api/windows.foundation.ireference-1) (the latter two being the only two heap-allocated field types).
https://learn.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system#structs
Not written on that doc page, but validated by midlrt is that `IReference<T>`'s in structs must be to value types, not to delegates, so the transitive closure of all types referenced by structs will always be sendable.
```
delegate void SomeDelegate();
struct OhNoNotInHere
{
Windows.Foundation.IReference<SomeDelegate> DelegateReference;
};
```
```
test_component.idl(483) : error MIDL5105 : [msg]T in …
```

Generate structs as Sendable

---

tests/test_component/Sources/CWinRT/include/test_component.h
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component.swift

Because I implemented https://github.com/thebrowsercompany/swift-winrt/pull/158 in `github.dev`.

Add missing checked-in generated code for vectorAsIterable

---

.github/actions/windows-build/action.yml
swiftwinrt/Resources/Support/WinRTProtocols.swift

We have seen a couple of instances of what looks like overrelease/memory corruption when subclassing across the WinRT bridge. It seems like swapping the order of the deinitialization here has an effect. I don't totally understand the model here so cc @stevenbrix to help explain

Swap order of _inner and identity cleanup

---

.github/actions/windows-build/action.yml

The action `compnerd/gha-setup-swift` was modified to skip calling `compnerd/gha-setup-vsdevenv` internally when swift is newer than 5.9, because this previously only done as part of a workaround where the swift compiler's module maps could not be located.  This is problematic because the latter sets environment variables necessary for the build, including PATH.
These actions were both pinned to `main` resulting in incompatible versions being used. They're now both pinned to the explicit commits on main (at the time of writing).

Pin gha-setup-vsdevenv

---

CMakePresets.json

Fixes the release CI workflow: https://github.com/thebrowsercompany/swift-winrt/actions/runs/9484234880/job/26133258865
It looks like there was a change/regression in CMake's handling of the `$penv{PATH}` expression, but in any case modifying the path is not necessary because the vs dev environment already includes the path to ninja.exe. We do not need this code for other CMake repos either.

Remove environment override in CMakePresets

---

.github/workflows/publish.yml

Follow-up to a postmortem where we couldn't deploy anymore due to a regression from a GitHub runner update.

Run the release build weekly

---

swiftwinrt/Resources/Support/Error.swift
swiftwinrt/code_writers.h
tests/test_component/Sources/test_component/Windows.Foundation+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.FileProperties+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.Search+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams+ABI.swift
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Generics.swift
tests/test_component/Sources/test_component/test_component.Delegates+ABI.swift

When an `Error` is caught by the projection, it needs to call `RoOriginateLanguageException` to capture the callstack and provide a message for the exception.
There is a lot more we should do to create a more complete experience, for example translating `HRESULT` -> `Error` at the API and caching the `Error` thrown so that we can resurface it in the `Application.unhandledException` callback. 
Right now, this is a first step which will hopefully help Arc get better error information in our traces.
Defaulting to returning `E_FAIL` for generic swift errors, since there are no "well-defined" exceptions in swift, i don't see an elegant way to translate an error to an `HRESULT`

capture the language exception

---

swiftwinrt/code_writers.h
swiftwinrt/file_writers.h
tests/test_app/DoubleDelegate+QueryInterface.swift
tests/test_component/Sources/test_component/Windows.Data.Text+ABI.swift
tests/test_component/Sources/test_component/Windows.Data.Text+Impl.swift
tests/test_component/Sources/test_component/Windows.Foundation+ABI.swift
tests/test_component/Sources/test_component/Windows.Foundation+Impl.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections+ABI.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.FileProperties+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.FileProperties+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.Search+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.Search+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams+Impl.swift
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Generics.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component.Delegates+ABI.swift
tests/test_component/Sources/test_component/test_component.Delegates+Impl.swift
tests/test_component/Sources/test_component/test_component.swift

this pr makes the internals public, since it doesn't affect the export count on debug builds and puts them all behind `@_spi(WinRTInternal)`. this will make it easier to fall back to something like this for accessing the throwing set/get of properties
```
let abi: __ABI_Microsoft_UI_Xaml.IFoo = try swift.thisPtr.QueryInterface()
let foo = try abi.get_Foo()
```

make internals public but behind spi

---

swiftwinrt/code_writers.h
tests/test_component/Sources/test_component/Windows.Foundation+ABI.swift
tests/test_component/Sources/test_component/Windows.Foundation+Impl.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections+ABI.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections+Impl.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections.swift
tests/test_component/Sources/test_component/Windows.Foundation.swift
tests/test_component/Sources/test_component/Windows.Storage+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.FileProperties+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.FileProperties+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.FileProperties.swift
tests/test_component/Sources/test_component/Windows.Storage.Search+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.Search+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.Search.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams.swift
tests/test_component/Sources/test_component/Windows.Storage.swift
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Generics.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component.Delegates+ABI.swift
tests/test_component/Sources/test_component/test_component.Delegates+Impl.swift
tests/test_component/Sources/test_component/test_component.swift

Remove `Impl` from ABI function calls
Now that these APIs are publically callable as fallbacks for when need to access throwing property set/get, having this extra `Impl` tacked onto the end is an eyesore. plus, it's totally not necessary

remove impl from ABI names

---

swiftwinrt/Resources/Support/Error.swift

Causes:
```
[107/751] Building Swift Module 'WindowsFoundation' with 50 sources
C:\Code\arc\build\debug\generated\Frameworks\WinRT\Sources\WindowsFoundation\Support\error.swift:184:9: warning: no calls to throwing functions occur within 'try' expression
182 |
183 |     do {
184 |         try message.withHStringRef {
|         `- warning: no calls to throwing functions occur within 'try' expression
185 |             _ = RoOriginateLanguageException(hresult, $0, nil)
186 |         }
C:\Code\arc\build\debug\generated\Frameworks\WinRT\Sources\WindowsFoundation\Support\error.swift:187:7: warning: 'catch' block is unreachable because no errors are thrown in 'do' block
185 |             _ = RoOriginateLanguageException(hresult, $0, nil)
186 |         }
187 |     } catch {
|       `- warning: …
```

Fix superfluous try/catch causing build warning

---

README.md

The WinGet package name for the 17763 version of the Windows SDK is 17736, erroneously. Specify it in the instructions.
Fixes #191

Fix WinGet install instructions

---

swiftwinrt/Resources/Support/Aggregation.swift
swiftwinrt/Resources/Support/WinRTWrapperBase.swift
swiftwinrt/code_writers.h
swiftwinrt/code_writers/common_writers.h
swiftwinrt/file_writers.h
tests/test_component/Sources/test_component/Windows.Foundation+ABI.swift
tests/test_component/Sources/test_component/Windows.Foundation+Impl.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections+Impl.swift
tests/test_component/Sources/test_component/Windows.Foundation.Collections.swift
tests/test_component/Sources/test_component/Windows.Foundation.swift
tests/test_component/Sources/test_component/Windows.Storage+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.FileProperties+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.FileProperties.swift
tests/test_component/Sources/test_component/Windows.Storage.Search+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.Search+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.Search.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams+ABI.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.Streams.swift
tests/test_component/Sources/test_component/Windows.Storage.swift
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Generics.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component.swift

This PR moves the WinRTClass to use the `AbiBridge` pattern for converting to/from the ABI. This makes the API more similar to the way interfaces work, and is a pre-cursor to array support
the bridge/contract pattern is required for classes/interfaces because they can not simply specify their abi convergence on the type themselves. as this would fail when trying to implement multiple interfaces or when using composable classes

have winrtclass also use the bridge pattern

---

swiftwinrt/Resources/Support/GUID.swift
swiftwinrt/Resources/Support/HString.swift
swiftwinrt/Resources/Support/Swift+Extensions.swift
swiftwinrt/Resources/Support/WinRTBridgeable.swift
swiftwinrt/code_writers/struct_writers.cpp
swiftwinrt/code_writers/struct_writers.h
swiftwinrt/file_writers.h
swiftwinrt/resources.rc
tests/test_component/Sources/test_component/Windows.Data.Text+Impl.swift
tests/test_component/Sources/test_component/Windows.Data.Text.swift
tests/test_component/Sources/test_component/Windows.Foundation+Impl.swift
tests/test_component/Sources/test_component/Windows.Foundation.swift
tests/test_component/Sources/test_component/Windows.Storage.Search+Impl.swift
tests/test_component/Sources/test_component/Windows.Storage.Search.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component.swift

This creates a `WinRTBridgeable` protocol to be used when converting arrays from Swift to WinRT. Could also be useful in other places, but currently no major code changes have been made. The existing `.from` method on the swift struct was moved to the extension which adheres to the `WinRTBridgeable` type

Create WinRTBridgeable protocol for simple converting to/from the ABI

---

.github/actions/windows-build/action.yml

Newer GitHub runners default to a Windows SDK that is not compatible with the Swift toolchain we use in the build.

Pin the Windows SDK to one compatible with our Swift toolchain

---

swiftwinrt/code_writers.h
swiftwinrt/code_writers/type_writers.cpp
swiftwinrt/code_writers/type_writers.h
tests/test_component/Sources/CWinRT/include/test_component.h
tests/test_component/Sources/test_component/test_component+ABI.swift
tests/test_component/Sources/test_component/test_component+Impl.swift
tests/test_component/Sources/test_component/test_component.swift
tests/test_component/cpp/ArrayTester.idl

properties of Array types were using IOUs in the defintion leading to compile errors. this pr fixes that
1. update `swift_write_type_params_for` to include an optional `is_array` boolean 
2. added a test interface which now compiles

dont use IOUs in array properties

---

.gitignore
CMakeLists.txt

When trying to build on my system, the varaible `CMAKE_SYSTEM_VERSION` defaults to `10.0.26100`, notice the missing `.0` at the end of the version number.
In my system the Windows Sdk is installed in `C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0` and not in `C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100`
So, while I try to understand why the default behaves like this, I modify the error to give the user a missing location:
```
CMake Error at CMakeLists.txt:7 (message):
Windows SDK Version appears not to be installed:
Missing folder: C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100
```
Side Note: Visual Studio, AdoDevOps and GitHub actions have started to gradually migrate away from VS components to NuGet packages.
This also applies for the Windows Sdk, instead of …

Provide better message when the Windows Sdk is not found
